### ISSUE TITLE
Support for SB8200?

### ISSUE THREAD

**Issue by subchromat** [billimek/SB6183-stats-for-influxdb#1]
Is there any chance you could add support for an Arris SB8200? I tried to run the docker image as-is but get:

```
docker start modemmonitor;docker logs -f modemmonitor
modemmonitor
Loading Configuration File config.ini
Configuration Successfully Loaded
Getting modem stats
Traceback (most recent call last):
  File "/src/SB6183.py", line 188, in <module>
    main()
  File "/src/SB6183.py", line 185, in main
    collector.run()
  File "/src/SB6183.py", line 145, in run
    self.parse_modem()
  File "/src/SB6183.py", line 95, in parse_modem
    'channel_id': int(channel_id),
ValueError: invalid literal for int() with base 10: 'SC-QAM'
```

**Comment by billimek** [comment]
Hi @DevinCampbell - probably not because I don't have access to that hardware and wouldn't know how to reference the specific page elements on that particular modem to pull the data from.

If it's something you want to figure out, we could work to re-organize this code to support multiple different modems which would be selected via a configuration item.

**Comment by subchromat** [comment]
I'm an extremely novice programmer so idk how much help I'd be. I have an SB8200 and I can provide you information if you'd be willing, but I understand if you don't want to.

**Comment by andrewfraley** [comment]
There's a bug in the SB8200 HTML where the table headers have an erroneous /tr thrown in.  Also, the td indexes are different and the SB8200 lacks the "channel" column for the downstream stats.  I created a new repo that will work for the SB8200 if someone wants it:  https://github.com/andrewfraley/arris_cable_modem_stats

I was going to add support for other modems and databases other than Influx, but time is precious.

**Comment by subchromat** [comment]
@andrewfarley That's awesome. I'm going to try it out and attempt to dockerize it.
